title: UHF 62
description: Web development specialising in Python and Django based in London, England.
email: hello@uhf62.co.uk
url: https://www.uhf62.co.uk
logo: /assets/logo.svg
lang: en_GB

social:
  name: UHF 62
  links:
    - http://linkedin.com/company/uhf62/
    - https://github.com/uhf62

collections:
  policies:
    output: true
  testimonials:
    output: false

defaults:
  - scope:
      path: ""
      type: "policies"
    values:
      layout: "policy"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Build settings
markdown: kramdown
